AWS_Web/category/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'category'
urlpatterns = [
    path('all', views.all, name='all'),
    path('detail/<str:title>', views.detail, name='detail'),
    path('select_seat/<str:title>', views.select_seat, name='select_seat'),
    path('reserved/<str:title>', views.reserved, name='reserved'),
]

AWS_Web/myticket/urls.py
from django.contrib import admin
from django.urls import path, include
from category.views import main
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('category/', include('category.urls')),
    path('users/', include('users.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AWS_Web/users/urls.py
from django.urls import path
from . import views 

app_name='users'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
]

AWS_Web/category/models.py
from django.db import models

class Performance(models.Model):
  genre = models.CharField(max_length=50, verbose_name="장르")
  title = models.CharField(max_length=100, verbose_name="제목", primary_key=True)
  image = models.ImageField(verbose_name="공연포스터", upload_to="category/images")
  date = models.DateField(auto_now=True, verbose_name="공연날짜")
  location = models.CharField(max_length=128, verbose_name="공연장소")
  member = models.CharField(max_length=128, verbose_name="출연진")
  overview = models.TextField(max_length=500, verbose_name="공연개요")

  def __str__(self):
    return self.title

  class Meta:
    db_table = 'performance'
    verbose_name = "공연"
    verbose_name_plural = "공연"



class PerformanceDetail(models.Model):
  title = models.ForeignKey('Performance', on_delete=models.CASCADE, db_column='title')

  ageGroup = models.CharField(max_length=20, verbose_name="관람 연령")
  viewingTime = models.CharField(max_length=20, verbose_name="관람 시간")
  priceVIP = models.CharField(max_length=20, verbose_name="VIP석")
  priceR = models.CharField(max_length=20, verbose_name="R석")
  priceS = models.CharField(max_length=20, verbose_name="S석")

  info_time = models.CharField(max_length=128, verbose_name="시간 안내")  # 몇시부터 몇시와 같이 상세한 시간 안내임
  info_delivery = models.CharField(max_length=128, verbose_name="티켓 배송 안내") # 아무렇게나 하면되는 배송 안내임

  def __str__(self):
    return str(self.title)

  class Meta:
    db_table = 'performance_detail'
    verbose_name = "공연 상세"
    verbose_name_plural = "공연 상세"

AWS_Web/users/models.py
from django.db import models


class SiteUsers(models.Model):
  username = models.CharField(max_length=5, verbose_name="성명")
  user_id = models.CharField(max_length=20, verbose_name="아이디", primary_key=True)
  password = models.CharField(max_length=128, verbose_name="비밀번호")
  telephone_number = models.CharField(max_length=128, verbose_name="전화번호")
  resident_number = models.CharField(max_length=128, verbose_name="주민번호")

  def __str__(self):
    return self.user_id

  class Meta:
    db_table = 'users'
    verbose_name = "회원"
    verbose_name_plural = "회원"

AWS_Web/category/views.py
from django.http import response, HttpResponse
from users.models import SiteUsers
from .models import Performance, PerformanceDetail
from django.shortcuts import get_object_or_404, redirect, render
from itertools import chain

# 모든 화면에 로그인 세션을 전달함
def main(request):
  user_id = request.session.get('user')
  datas = {}
  
  if user_id:
    datas['user_id'] = SiteUsers.objects.get(pk=user_id)

  datas['performance'] = Performance.objects.all()
  return render(request, 'index.htm', datas)


def all(request):
  user_id = request.session.get('user')
  datas = {}

  if user_id:
    datas['user_id'] = SiteUsers.objects.get(pk=user_id)
  return render(request, 'all.htm', datas )


def detail(request, title):
  user_id = request.session.get('user')
  datas = {}

  if user_id:
    datas['user_id'] = SiteUsers.objects.get(pk=user_id)
  else : # 로그인하지 않으면 좌석선택 버튼 비활성화
    datas['error'] = '로그인이 필요합니다'
  
  # main,all 페이지에서 공연 클릭시 'title' 값을 전달(고유한값)
  # 공연 상세 품목을 DB에서 조회
  a = Performance.objects.filter(title=title).all()
  b = PerformanceDetail.objects.filter(title=title).values()
  datas['performance'] = a
  datas['performance_detail'] = b
  
  return render(request, 'detail.htm', datas )


def select_seat(request, title):
  user_id = request.session.get('user')
  datas = {}

  if user_id:
    datas['user_id'] = SiteUsers.objects.get(pk=user_id)

    if request.method == 'GET': # 평상시 실행되는 코드 화면만 불러옴
      a = Performance.objects.filter(title=title).all()
      b = PerformanceDetail.objects.filter(title=title).values()
      datas['performance'] = a
      datas['performance_detail'] = b
      return render(request, 'select_seat.htm', datas )
      
    elif request.method == 'POST': # 예매하기 버튼을 눌렀을 경우 실행되는 코드
      datas['reserved'] = str(request.POST.get('seat', None)).split(':')
      print(datas)

      return render(request, 'reserved.htm', datas )


def reserved(request, title):
  user_id = request.session.get('user')
  datas = {}

  if user_id:
    datas['user_id'] = SiteUsers.objects.get(pk=user_id)
  
  if request.method == 'POST': # 예매하기 버튼을 눌렀을 경우 실행되는 코드
    datas['reserved'] = str(request.POST.get('seat', None)).split(':')
    a = Performance.objects.filter(title=title).all()
    b = PerformanceDetail.objects.filter(title=title).values()
    datas['performance'] = a
    datas['performance_detail'] = b
    print(a)
    print(b)
    return render(request, 'reserved.htm', datas )
  else :
    raise HttpResponse("fhtq")

AWS_Web/users/views.py
from django.contrib.auth import get_user_model
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from .models import SiteUsers
from django.contrib.auth.hashers import check_password, make_password

# Create your views here.
def login(request):
  if request.method == 'GET':
    return render(request, 'login.htm')

  elif request.method == 'POST':
    user_id = request.POST.get('user_id', None)
    password = request.POST.get('password', None)
    responsed_data = {}
    if not (user_id and password):
      responsed_data['error'] = '아이디와 비밀번호를 모두 입력하세요'
      return render(request, 'login.htm', responsed_data)
    else:
      siteUser = SiteUsers.objects.get(user_id=user_id)
      if check_password(password, siteUser.password):
        request.session['user'] = siteUser.user_id # 로그인 성공, 세션 생성
        return redirect('main')
      else:
        responsed_data['error'] = '비밀번호를 다시 확인해주세요'
        return render(request, 'login.htm', responsed_data)


def logout(request):
  if request.session.get('user'):
    del(request.session['user'])
    request.session.flush()
  return redirect('main')        


def register(request):
  # 회원가입 신청시 호출되는 곳
  if request.method == 'POST':
    username = request.POST.get('username', None)
    user_id = request.POST.get('user_id', None)
    password = request.POST.get('password', None)
    password_verify = request.POST.get('password_verify', None)
    telephone_number = request.POST.get('telephone_number', None)
    resident_number = str(request.POST.get('resident_front', None)) + str(request.POST.get('resident_back', None))
    responsed_data = {}
    if not( username and user_id and password and password_verify ):
      responsed_data['error'] = '모든 값을 입력하세요'
      return render(request, 'register.htm', responsed_data)
    elif SiteUsers.objects.filter(user_id=user_id).exists():
      responsed_data['error'] = '아이디를 이미 사용중입니다'
      return render(request, 'register.htm', responsed_data)
    elif password != password_verify:
      responsed_data['error'] = '비밀번호가 다릅니다'
      return render(request, 'register.htm', responsed_data)  
    else:
      siteUsers = SiteUsers(
        username = username,
        user_id = user_id,
        password = make_password(password),
        telephone_number = telephone_number,
        resident_number = resident_number
      )
      siteUsers.save()
    return redirect('main')

  # GET 요청일 경우 회원가입 페이지 호출
  return render(request, 'register.htm')

AWS_Web/category/templates/all.htm
{% extends 'base.htm' %}
{% load static %}

{% block head %}
  <style type="text/css">
    section, aside{
      float: left;
    }

    section {
      width: 60%;
    }
    aside {
      width: 20%;
    }
  </style>
{% endblock %}


{% block main %}
<main>

  <aside>
    <p></p>
  </aside>
  <section>
    <div class="category_title">
      <h1>콘서트</h1>
    </div>
    <div class="row mb3">
      <div class="col-md-2 themed-grid-col">
        <img src="{% static 'img/parasite.png' %}" width='200px' height='auto' alt="">
      </div>
      <div class='col-md themed-grid-col'>
        <div class="bg-light p-5 rounded">
          <p class="lead">콘서트 > 국내</p>
          <br>
          <h1>2021 박효신 콘서트[사랑, 추억]</h1>
          <p class="lead">2021.07.10 ~ 2021.07.10</p>
          <!-- 파라미터 넘겨야함 ㅠ-->
          <a class="btn btn-lg btn-primary" href="{% url 'detail'  %}" role="button">상세정보</a>
        </div>
      </div>
    </div>
    
    <hr class="my-4">
    
    <div class="row mb3">
      <div class="col-md-2 themed-grid-col">
        <img src="{% static 'img/parasite.png' %}" width='200px' height='auto' alt="">
      </div>
      <div class='col-md themed-grid-col'>
        <div class="bg-light p-5 rounded">
          <p class="lead">콘서트 > 국내</p>
          <br>
          <h1>2021 박효신 콘서트[사랑, 추억]</h1>
          <p class="lead">2021.07.10 ~ 2021.07.10</p>
          <a class="btn btn-lg btn-primary" href="/docs/5.0/components/navbar/" role="button">상세정보</a>
        </div>
      </div>
    </div>
    
    <hr class="my-4">
    
    <div class="row mb3">
      <div class="col-md-2 themed-grid-col">
        <img src="{% static 'img/parasite.png' %}" width='200px' height='auto' alt="">
      </div>
      <div class='col-md themed-grid-col'>
        <div class="bg-light p-5 rounded">
          <p class="lead">콘서트 > 국내</p>
          <br>
          <h1>2021 박효신 콘서트[사랑, 추억]</h1>
          <p class="lead">2021.07.10 ~ 2021.07.10</p>
          <a class="btn btn-lg btn-primary" href="/docs/5.0/components/navbar/" role="button">상세정보</a>
        </div>
      </div>
    </div>
    
    <hr class="my-4">
    
    <div class="row mb3">
      <div class="col-md-2 themed-grid-col">
        <img src="{% static 'img/parasite.png' %}" width='200px' height='auto' alt="">
      </div>
      <div class='col-md themed-grid-col'>
        <div class="bg-light p-5 rounded">
          <p class="lead">콘서트 > 국내</p>
          <br>
          <h1>2021 박효신 콘서트[사랑, 추억]</h1>
          <p class="lead">2021.07.10 ~ 2021.07.10</p>
          <a class="btn btn-lg btn-primary" href="/docs/5.0/components/navbar/" role="button">상세정보</a>
        </div>
      </div>
    </div>
  </section>
  <aside>
    <p></p>
  </aside>
</main>
  {% endblock%}

AWS_Web/category/templates/base.htm
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>문화의 시작 MyTicket</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/headers/">

    <!-- base CSS files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/headers.css' %}" rel="stylesheet">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/product.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
    <!-- Custom styles in this template -->
    {% block head %}
    {% endblock %}
  </head>

  <body>
    <div class="container">
      <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="{% url 'main' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
          <img class="bi me-2" role="img" src="{% static 'img/logo.png' %}" width="auto" height="120px"/>
        </a>
        <div class="col-md-5 text-end">
          {% if user_id %}
            <button type="button" class="btn btn-outline-primary me-2">{{ user_id }}</button>
            <button type="button" onclick = "location.href = '/users/logout' " class="btn btn-outline-primary me-2">로그아웃</button>
          {% else %}  
            <button type="button" onclick = "location.href = '/users/login' " class="btn btn-outline-primary me-2">로그인</button>
          {% endif %}
          <button type="button" onclick = "location.href = '/users/register' "  class="btn btn-primary">회원가입</button></a>
        </div>
      </header>
    </div>
    <div class="container2">
      <header class="site-header sticky-top py-1">
        <nav class="container d-flex flex-column flex-md-row justify-content-between">
          <a class="py-2 d-none d-md-inline-block" href="#">콘서트</a>
          <a class="py-2 d-none d-md-inline-block" href="#">뮤지컬</a>
          <a class="py-2 d-none d-md-inline-block" href="#">연극</a>
          <a class="py-2 d-none d-md-inline-block" href="#">오케스트라</a>
          <a class="py-2 d-none d-md-inline-block" href="#">페스티벌</a>
        </nav>
      </header>
      
    {% block main %}
    {% endblock %}
  </body>
</html>

AWS_Web/category/templates/detail.htm
{% extends 'base.htm' %}
{% load static %}


{% block head %}
  <style type="text/css">
    section, aside{
      float: left;
    }

    section {
      width: 60%;
    }
    aside {
      width: 20%;
    }
    .message{
      text-align: center;
      margin: 45px;
    }
  </style>
{% endblock %}


{% block main %}
<aside>
  <p></p>
</aside>
<section>
  <div class="message"><h2>공연 상세정보</h2></div>
  <div class='col-md themed-grid-col'>
    <div class="bg-light p-3 rounded" >
      {% for data in performance %}
      <h1>[{{ data.genre }}] {{ data.title }}</h1>
      <p>{{ data.date }}</p>
      {% endfor %}
    </div>
    <hr class="my-4">
    
    <div class="row mb-3">
      <div class="col-md-5 themed-grid-col">

        <img src="{{ performance.0.image.url }}" width='400px' height='auto'>
      </div>
      <div class="col-md">
        <div class="row mb-10">
          <div class="col-md-3">
            <p>등급</p>
            <p>관람시간</p>
            <p>출연</p>
            <p>가격</p>
          </div>
      {% for data in performance_detail %}
          <div class="col-md">
            <p>{{ data.ageGroup }}</p>
            <p>{{ data.viewingTime }}</p>
            <p>{{ performance.0.member }}</p>
            <div class="price_box bg-light">
              <p>&nbsp;VIP석&nbsp;&nbsp;{{ data.priceVIP }}원</p>
              <p>&nbsp;R석&nbsp;&nbsp;{{ data.priceR }}원</p>
              <p>&nbsp;S석&nbsp;&nbsp;{{ data.priceS }}원</p>
            </div>
          </div>
        </div>
        <hr class="my-4">
        <div class="col-md">
          <div class="row mb-10">
            <div class="col-md-3">
              <p>시간 안내</p>
              <p>장소 안내</p>
              <p>티켓 배송 안내</p>
            </div>
            <div class="col-md">
              <p>{{ data.info_time }}</p>
              <p>{{ performance.0.location }}</p>
              <p>{{ data.info_delivery }}</p>
            </div>
          </div>
        </div>
        <br>
        {% if error %}
        <a class="1btn btn-lg btn-primary" href="{% url 'category:detail' title=data.title_id %}" role="button" >좌석선택</a>
        {% else %}
        <a class="1btn btn-lg btn-primary" href="{% url 'category:select_seat' title=data.title_id %}" role="button" >좌석선택</a>
        {% endif %}
        <span style="color: red;">&nbsp;&nbsp;&nbsp;{{ error }}</span> <!-- &nbsp; 는 공백-->
        {% endfor %}
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>
    </div>
  </section>
  <aside>
    <p></p>
  </aside>
  {% endblock %}

AWS_Web/category/templates/index.htm
{% extends 'base.htm' %}
{% load static %}

{% block head %} 
{% endblock %}

{% block main %}
  <main>
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <!-- if 상영날짜 <= today + 20일 = 개봉예정-->
    <!-- if 상영날짜 == today 상영중-->
    <br>
    <br>
    <br>
    <div class="container marketing">
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <h1 class="content_head text-center">진행중인 공연</h2>
      </div>
      <div class="row" style="text-align: center;">
        
        {% for per in performance %}
        <div class="col-lg-6" style="padding: 50px 10px;" >
          <a href="{% url 'category:detail' title=per.title %}"><img src="{{ per.image.url }}" width='auto' height='400px'></a>
          <h4>[{{per.genre|default:'미정'}}] {{per.title}}</h4>
          <span class="text-muted">{{ per.date }} <br> {{per.location}}</span>
          <p class="lead">출연진 : {{ per.member }}</p>
          <span class="text-muted">{{ per.overview }}</span><p></p>
          <p><a class="btn btn-secondary" href="{% url 'category:detail' title=per.title %}">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        {% endfor %}
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">
      <h1 class="content_head text-center">예정 공연</h2>
              
      <div class="row featurette">
        <div class="col-md-7">
          <h3 class="featurette-heading">[페스티벌]<br> 자라섬 재즈 & 힙합 축제 </h3>
          <span class="text-muted">2021년 8월 17일 / 강원도 - 자라섬 </span>
          <br>
          <p class="lead">빈지노·나윤선·전인권·더콰이엇·켄드릭 라마·콜드 플레이<br>윤딴딴·O.O.O·심현보·김필·정승환·10CM·자이언티·크러쉬·헤이즈</p>
          <p >각 아티스트당 25분 공연. 총 2부 <br> 1부 : 오후 2시 ~ 오후 4시 <br> 2부 : 오후 6시 ~ 오후 9시</p>
        </div>
        <div class="col-md-5">
          <img src="{% static 'img/zarasum.jpg' %}" width="auto" height="400px">
        </div>
      </div>
      
      <hr class="featurette-divider">
      
      <div class="row featurette">
        <div class="col-md-6 order-md-2">
          <h3 class="featurette-heading">[페스티벌]<br> 온 가족이 즐기는 <br>경량 클래식 공연 </h3>
          <span class="text-muted">2021년 8월 2일 / 서울 - 난지공원</span>
          <br>
          <p class="lead">이루마 · 전수연</p>
          <p >이루마, 전수연의 합동 공연. 총 1부 <br> 1부 : 오후 7시 ~ 오후 9시</p>
        </div>
        <div class="col-md-6 order-md-1">
          <img src="{% static 'img/nanji.jpg' %}" width="400px" height="auto">
        </div>
      </div>
      
      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h3 class="featurette-heading">[페스티벌]<br> KB와 함께하는 <br>Let's Rock 10주년 축제</h3>
          <span class="text-muted">2021년 7월 23일 / 서울 - 난지공원</span>
          <br>
          <p class="lead">어반자카파·장법준·스탠딩에그·짙은·오존·제이레빗·바닐라어쿠스틱<br>윤딴딴·O.O.O·심현보·김필·정승환·10CM·자이언티·크러쉬·헤이즈<br>옥상달빛·분리수거·넬·임재범·우주소녀·볼빨간사춘기·전효성</p>
          <p >각 아티스트당 15분씩 공연. 총 2부<br> 1부 : 오전10시 ~ 오후2시<br> 2부 : 오후3시 ~ 오후5시</p>
        </div>
        <div class="col-md-5">
          <img src="{% static 'img/letsRock.jpg' %}" width="400px" height="auto">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->


    <!-- FOOTER -->
    <footer class="container">
      <p class="float-end"><a href="#">Back to top</a></p>
      <p>© 2020–2021 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>
  </main>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
{% endblock  %}

AWS_Web/category/templates/reserved.htm
{% extends 'base.htm' %}
{% load static %}

{% block head %}
<style type="text/css">
  section, aside{
    float: left;
  }

  section {
    width: 60%;
  }
  aside {
    width: 20%;
  }
  
  .accent{
    color: red;
  }
  .message{
    text-align: center;
    margin: 45px;
  }
</style>
{% endblock %}

{% block main %}

<aside>
  <p></p>
</aside>

<section>
  <div class="message"><h2>예매 완료</h2></div>
  <hr class="my-4">
  <div class='col-md themed-grid-col'>
    <div class="bg-light p-5 rounded">
      {% for data in performance %}
      <h1>[{{ data.genre }}] {{ data.title }}</h1>
      <br>
      <p class="lead">공연일시 : {{ data.date }}</p>
      {% endfor %}
    </div>
  </div>
  <div class="row mb-10" style="padding: 20 15;">
      <div class="col-md-5">
        <div class="row mb-10 bg-light">
          <div class="col-md-4">
            <p>구매자명</p>
            <p>좌석번호</p>
            <p>시간안내</p>
            <p>장소안내</p>
            <p>티켓 배송안내</p>
          </div>
          <div class="col-md">
            <p class="accent"> {{ user_id }}</p>
            <p class="accent"> {{ reserved.0 }}열 {{ reserved.1 }}번</p>
            <p>{{ performance_detail.0.info_time }}</p>
            <p>{{ performance.0.location }}</p>
            <p>{{ performance_detail.0.info_delivery }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
 <br>
 <br>
 <br>
 <br>
</section>

<aside>
  <p></p>
</aside>

{% endblock %}

AWS_Web/category/templates/select_seat.htm
{% extends 'base.htm' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/select_seat.css' %}">
<script src="http://code.jquery.com/jquery-latest.js"></script>
{% endblock %}

{% block main %}
<!-- Author information
* html, php, css, javascript
*   written by hepheir@gmail.com
*

* site designed by
*   dfc7936@naver.com & hepheir@gmail.com
*
-->

<div id="bodyWrap">
  <div id="stageWrap">
      <form class="" action="{% url 'category:reserved' title=performance.0.title %}" method="post">
        {% csrf_token %}
        <div class="p-3 container rounded">
          {% for data in performance %}
          <h2>좌석선택</h2>
          <h1>[{{ data.genre}}] {{ data.title }}</h1>
          <p class="lead">공연일시 : {{ data.date }}</p>
         {% endfor %} 
        </div>
        <br>
      <h1 class="stage container" style="width: 50%; padding: 20px; background-color: green; color:white ">stage</h1>
      <br>
      <br>
      <div id="stageTable">
        <table>
          <script>
            // 가로 : 행
            // 세로 : 열
            var cols = 30; //행
            var rows = 10; //열
            var i = 0;
            var j = 1;
            var c = String.fromCharCode(i + 65);

            while (i < rows) {
              document.write('<tr>');
              while (j <= cols) {
                document.write('<td class="cell" style="border: 1px solid black; text-align: center"><input type="radio" id="seat_' + c + j + '" class="hidden" name="seat" value="' + c + ':' + j + '"/><label for="seat_' + c + j + '" class="cell">' + c + j + '</label></td>');
                j++;
              }
              document.write('</tr>');
              j = 1;
              i++;
              c = String.fromCharCode(i + 65);
            }
          </script>
        </table>
        <input id="done" name="part" class="hidden" type="submit" />
        <label class="console_2" for="done"><strong>예매하기</strong></label>
      </form>
    </div>
</div>
{% endblock %}

AWS_Web/users/templates/login.htm
{% load static %}

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Ticket Monster</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}"  rel="stylesheet">
  </head>

  <!-- 아이디 비밀번호 찾기 -->
  <body class="text-center">
    <main class="form-signin">
      <a href="{% url 'main' %}">
      <img class="mb-4" src="{% static 'img/logo_login.png' %}" alt="" width="auto" height="100">
      </a>
      <h1 class="h4 mb-4 fw-normal">Enjoy for login!</h1>
      
      <form method="POST" action="/users/login" >
        {% csrf_token %}
        <div class="form-floating">
          <input type="text" class="form-control" id="user_id" name='user_id' autofocus placeholder="ID">
          <label for="user_id">아이디</label>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" id="password" name='password' placeholder="Password">
          <label for="password">비밀번호</label>
        </div>
        
        {{ error }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">로그인</button>
      </form>
      <p class="mb-1">&copy; 2020–2021 <a href="/">Ticket Monster</a></p>
    </main>
  </body>
</html>